void ceiling_message(struct Buckeye *brutus);
void final_output(struct Sim *world);
void flag_message(struct Buckeye *brutus);
void floor_message(struct Buckeye *brutus);
void jump_message(struct Buckeye *brutus);
void loot_message(struct Buckeye *brutus);
void master_output(struct Sim *world);
void node_allocate_out();
void node_free_out();
void output_bad_bits(unsigned short code);
void output_scanf(int tokens);
char *team(int c);
